#! /usr/bin/python
# -*- coding: utf-8 -*-

import rospy
from std_msgs.msg import String
from robot_skills.amigo import Amigo

rospy.init_node('emoticon_handler')
robot = Amigo()

def pp(msg):
    pub.publish(String(data=msg))
    rospy.loginfo(msg)
    robot.speech.speak(msg, block=False)

def cb(msg):
    text = msg.data
    if text == "🌈":
        robot.lights.taste_the_rainbow()
        pp("Taste the rainbow baby")
    if text == "❤":
        pp("I love you too!")
    if text == "🍆":
        pp("Let's save that for later!")
    if text == "📷":
        pp("Cheese!")
    if text == "🤖":
        pp("I am a robot, beep boop beep!")


rospy.Subscriber("/amigo/message_from_telegram", String, cb)
pub = rospy.Publisher("/amigo/message_to_telegram", String, queue_size=1)
rospy.loginfo("Emoticon handler spinning ...")
rospy.spin()
