#!/usr/bin/env python

import rospy
import tf
from geometry_msgs.msg import PoseStamped, Quaternion

import random
import math

random.seed()

rospy.init_node("ssl_dummy")
frame_id = rospy.get_param("~frame_id", "matrix")
pub = rospy.Publisher("ssl/direction_of_arrival", PoseStamped, queue_size=1)

r = rospy.Rate(2)
while not rospy.is_shutdown():
    q = Quaternion()
    q.x, q.y, q.z, q.w = tf.transformations.quaternion_from_euler(0, 0, math.pi * 2 * random.random())

    msg = PoseStamped()
    msg.header.stamp = rospy.Time.now()
    msg.header.frame_id = frame_id

    msg.pose.orientation = q

    pub.publish(msg)

    r.sleep()

